### ISSUE TITLE
Bug Report: inferred_value doesn't propagate to the subscript of a list

### ISSUE THREAD

**Issue by erezsh** [quora/pyanalyze#207]
The following code demonstrates the bug:

```
a = [1,2,3]

if a[:0]:
	print("// bad")

import pyanalyze
def main():
	tree = pyanalyze.ast_annotator.annotate_file(__file__)
	print(repr(tree.body[1].test.inferred_value))			# UnresolvedValue()
	print(repr(tree.body[1].test.value.inferred_value))		# KnownValue(val=[1, 2, 3])

main()
```

The issue from my standpoint, is that when I ask for the type of the if's condition, I get `None` instead of `list`, even though there should be no doubt that it is a list.

I'd be willing to attempt to fix it myself, if you could give me a few pointers.

Btw,

Your library has been very useful to me so far, to establish call graphs and discern types, so thank you!

**Comment by JelleZijlstra** [comment]
Thanks for the report! The issue here is actually that pyanalyze doesn't deal with `list.__getitem__` at all. This is basically an instance of #64, a place where it unexpectedly isn't able to infer something.

Subscripts get handled in https://github.com/quora/pyanalyze/blob/master/pyanalyze/name_check_visitor.py#L3327. It has some special cases for SequenceIncompleteValue, so you'll see int subscripts work for some cases where pyanalyze has a precise type, but for general lists it will just fall back to the return type of `list.__getitem__`. Because that method is overloaded in typeshed (https://github.com/python/typeshed/blob/master/stdlib/builtins.pyi#L776), pyanalyze doesn't know what to do with it and just returns Any.

This isn't exactly going to be trivial to fix. I see two ways out:
- Add support for overloads (#182). That's going to be a pretty big project. I'll probably take it on after I get protocols working, but it may be a while.
- Add an implementation function for `list.__getitem__` in implementations.py, similar to the existing one for `dict.__getitem__`. Doing this will allow us to get rid of some more special casing in name_check_visitor.py. We'd also want a very similar impl for `tuple.__getitem__`.

The second option shouldn't be too hard if you're interested in taking it on. I'd recommend looking at the existing implementation functions for `dict.__getitem__` and other `list` methods as examples.

(Also, sorry for not responding earlier; I was out of town.)

**Comment by JelleZijlstra** [comment]
#241 should fix this.

**Comment by erezsh** [comment]
Nice!

I'm glad to see there's so much recent activity. Mind if I ask what's your new goal?

**Comment by JelleZijlstra** [comment]
An internal use case came up that required some pyanalyze changes. While implementing that I noticed a bunch of other bugs that affected us, so I decided to fix them. The one from #242 is especially nasty; I still have a lot of things I need to fix internally before I can merge that one. I'm thinking of cutting a release once I get all these resolved.
