### ISSUE TITLE
Provide a summary of how pyanalyze complements/compares with static analyzers and type checkers

### ISSUE THREAD

**Issue by CAM-Gerlach** [quora/pyanalyze#212]
After digging in to the readme and trying it out for myself, I think I'm starting to develop a decent understanding of how pyanalyze works and what it does, at least in isolation. However, even after all that as well as fair amount of experience with multiple linters/static analyzers (flake8, pylint, etc) as well as type checkers (mypy), I'm left a little uncertain where pyanalyze is intended to fit in within the broader ecosystem. After looking into it, it seems clear that it does things differently and offers unique value over those options, but not really obvious how or why.

As a user interested in this tool, this was the first question I had when stumbling across the project, and while I've started to put together bits and pieces, I'm still not entirely clear on high level answer. If I'm already using flake8, pylint, mypy, etc, what does pyanalyze offer me? How does it complement (or even replace) some of those tools? If I'm not using a tool like this, what are the reasons to use pyanalyze? If it hadn't been for my natural curiosity and recognizing your relatively well-known name, given it wasn't immediately clear how much it offered over the other tools I'm already using.

While more detail would be a bonus, it doesn't have to be a point by point comparison or anything—even a few sentences worth of high-level overview explaining the motivation for making a new tool and how pyanalyze fits into the ecosystem would be really helpful, not only to informing users but also helping attract new ones. That's something only you can answer, but I'd be happy to copyedit and give feedback on it if you'd like. Thanks!

**Comment by JelleZijlstra** [comment]
Yes, the documentation definitely is lacking—I did a bit of work in that direction but didn't get to high-level concepts like this. https://pyanalyze.readthedocs.io/en/latest/ now has some decent content on individual modules but nothing on overall usage yet. I am planning to get back to that once I get some time.

The biggest thing that sets pyanalyze apart from other type checkers is that it imports the code and uses some runtime inspection, which means it can understand dynamic pieces of Python code that other, fully static type checkers won't understand.

Another unique aspect is the support for the asynq framework which we use internally at Quora. This is a big one for us because we have millions of lines of code built on asynq, but it's less compelling for the rest of the world which doesn't use asynq.

**Comment by JelleZijlstra** [comment]
This is now covered in https://github.com/quora/pyanalyze/blob/master/docs/faq.md.

**Comment by CAM-Gerlach** [comment]
Great, that's fantastic @JelleZijlstra ! Thanks so much!
