### ISSUE TITLE
using pyanalyze with bazel

### ISSUE THREAD

**Issue by naranbayanbat-glean** [quora/pyanalyze#693]
is there support / guide for using pyanalyze for a project that uses bazel build?

**Comment by JelleZijlstra** [comment]
Hi Naran! I've never used Bazel myself or know much about it, so I can't help much. Probably to make pyanalyze work with Bazel you'd take a similar approach as you'd use for running unit tests, because in both cases the tool needs to run in an environment with all the project's dependencies installed.

**Comment by naranbayanbat-glean** [comment]
Makes sense, thanks Jelle!
