### ISSUE TITLE
Handle literal value with parameter tuple that has parentheses

### ISSUE THREAD

**Issue by Glyphack** [quora/pyanalyze#707]
According to [typing spec](https://github.com/JelleZijlstra/typing-spec/blob/main/spec/spec.rst?rgh-link-date=2023-11-07T21%3A51%3A06Z#illegal-parameters-for-literal-at-type-check-time) tuple value inside a Literal type annotation is not allowed.

I'm not familiar with the code but while I was playing around in #706  with it If found that the Literal value with a tuple parameter is treated the same with and without parentheses.

Is this intended behavior?

By the way Python ast parses these two expressions the same so finding out this would be difficult:

```
>>> print(ast.dump(ast.parse("s[(0,0)]")))
Module(body=[Expr(value=Subscript(value=Name(id='s', ctx=Load()), slice=Tuple(elts=[Constant(value=0), Constant(value=0)], ctx=Load()), ctx=Load()))], type_ignores=[])
>>> print(ast.dump(ast.parse("s[0,0]")))
Module(body=[Expr(value=Subscript(value=Name(id='s', ctx=Load()), slice=Tuple(elts=[Constant(value=0), Constant(value=0)], ctx=Load()), ctx=Load()))], type_ignores=[])
```

Does it worth to open an issue on Python repo about this?

**Comment by JelleZijlstra** [comment]
As you say, this is difficult to fix in pyanalyze because the AST doesn't distinguish between these cases. I'm personally not too bothered by this problem so I'm unlikely to introduce any new complexity to deal with it.

Possibly the Python AST could be changed to distinguish these cases, but I'm not sure that's likely. Before you open a CPython issue, I'd recommend coming up with a concrete proposal for what the AST should look like in both cases.

Closing as there's nothing here for pyanalyze to change.
